on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Lint Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v11
        with:
          globs: |
            *.md
            !test/*.md
